<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-0GOSDQT" name="smokeTests.MainPage" tests="9" failures="1" timestamp="14 Nov 2018 22:10:34 GMT" time="152.252" errors="0">
  <testcase name="mainpageBasketPresent" time="5.311" classname="smokeTests.MainPage"/>
  <testcase name="resultsBlockPresent" time="5.914" classname="smokeTests.MainPage">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at smokeTests.MainPage.resultsBlockPresent(MainPage.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- resultsBlockPresent -->
  <testcase name="AccountCorrectDestination" time="41.889" classname="smokeTests.MainPage"/>
  <testcase name="mainpageAccountPresent" time="25.734" classname="smokeTests.MainPage"/>
  <testcase name="searchBarPresent" time="5.498" classname="smokeTests.MainPage"/>
  <testcase name="mainpageTitleCorrect" time="5.272" classname="smokeTests.MainPage"/>
  <testcase name="BasketCorrectDestination" time="9.709" classname="smokeTests.MainPage"/>
  <testcase name="LogoCorrectDestination" time="47.971" classname="smokeTests.MainPage"/>
  <testcase name="mainpageLogoPresent" time="4.954" classname="smokeTests.MainPage"/>
</testsuite> <!-- smokeTests.MainPage -->
